#!/bin/bash
set -eu

#exec /lustre/software/R/R-3.3.2/bin/Rscript /lustre/software/SEQUELstats/SEQUELstats_20171017/SEQUEL_plot.R "$@"
exec /lustre/software/R/R-3.3.2/bin/Rscript "$(dirname $BASH_SOURCE)"/../SEQUELstats_20171017_patched/SEQUEL_pipe.sh "$@"
