#!/bin/sh

# Run a SMRTLink tool (specific version)

# Try:
# smrt dataset ---help
# smrt python3 -m pbcoretools.tasks.dataset_filter --help

smrt_bin=/lustre-gseg/software/pacbio_smrttools/smrttools_10.1.0.119588/smrtcmds/bin

if [ -z "$*" ] ; then
    echo
    echo "usage: smrt <program> [args]"
    echo
    echo "Tools available in $smrt_bin:"
    ls "$smrt_bin"
else
    # Disable core dumps
    ulimit -c 0

    exec env PATH="$smrt_bin:$PATH" "$@"
fi
